app/views/main_views.py
from flask import Blueprint, redirect, render_template
from flask import request, url_for
from flask_user import current_user, login_required, roles_required
from datetime import datetime
from app import db
from app.models import UserProfileForm, Ticket, TicketStatus, TicketForm
from flask.helpers import flash

main_blueprint = Blueprint("main", __name__, template_folder="templates")


# The Home page is accessible to anyone
@main_blueprint.route("/")
def home_page():
    return render_template("main/home_page.html")


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route("/user", methods=["GET", "POST"])
@login_required  # Limits access to authenticated users
def user_page():
    ticket = Ticket(
        requester_id=current_user.id,
        status=TicketStatus.OPEN,
        create_date=datetime.now(),
    )
    form = TicketForm(request.form, obj=ticket)

    print(current_user)
    print(current_user.__dict__)
    print(current_user.id)
    if form.validate_on_submit():
        # Copy form fields to user_profile fields
        form.populate_obj(ticket)

        # Save ticket
        db.session.add(ticket)
        db.session.commit()

        # reset form and      flash success

        flash("Successfully created ticket", "success")
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(
                    "Error in the %s field - %s"
                    % (getattr(form, field).label.text, error),
                    "error",
                )

    # Pull all tickets requested by this user for display
    tickets = current_user.requested_tickets

    return render_template("main/user_page.html", form=form, tickets=tickets)


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route("/admin")
@roles_required("admin")  # Limits access to users with the 'admin' role
def admin_page():
    return render_template("main/admin_page.html")


@main_blueprint.route("/main/profile", methods=["GET", "POST"])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if form.validate_on_submit():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for("main.home_page"))

    # Process GET or invalid POST
    return render_template("main/user_profile_page.html", form=form)


@main_blueprint.route("/ticket/<int:ticket_id>", methods=["GET"])
@login_required
def ticket_page(ticket_id):
    ticket = Ticket.query.filter(Ticket.id == ticket_id).one()
    return render_template("main/ticket_page.html", ticket=ticket)

app/templates/main/admin_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>Admin Page</h2>
    <p><a href={{ url_for('user.register') }}>Register</a></p>
    <p><a href={{ url_for('user.login') }}>Sign in</a></p>
    <p><a href={{ url_for('main.home_page') }}>Home Page</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.user_page') }}>User Page</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>Admin Page</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>Sign out</a></p>
{% endblock %}

app/templates/main/home_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>Home page</h2>
    <p><a href={{ url_for('user.register') }}>Register</a></p>
    <p><a href={{ url_for('user.login') }}>Sign in</a></p>
    <p><a href={{ url_for('main.home_page') }}>Home Page</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.user_page') }}>User Page</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>Admin Page</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>Sign out</a></p>
{% endblock %}

app/templates/main/main_base.html
{% extends "layout.html" %}

app/templates/main/ticket_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>Tickets page</h2>
    <br/>
    <h3>{{ ticket.title }}</h3>
    <br/>
    <p>{{ ticket.description }}</p>
    <br/>
    <ul>
        <li>status - {{ ticket.status }}</li>
        <li>create date - {{ ticket.create_date }}</li>
        <li>requester - {{ ticket.requester.first_name }}</li>
        <li>assignee - {{ ticket.assignee.first_name | default("None", true) }}</li>
    </ul>
{% endblock %}

app/templates/main/user_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>Users page</h2>
    <div>
        <p><a href={{ url_for('user.register') }}>Register</a></p>
        <p><a href={{ url_for('user.login') }}>Sign in</a></p>
        <p><a href={{ url_for('main.home_page') }}>Home Page</a> (accessible to anyone)</p>
        <p><a href={{ url_for('main.user_page') }}>User Page</a> (login_required: member@example.com / Password1)</p>
        <p><a href={{ url_for('main.admin_page') }}>Admin Page</a> (roles_required: admin@example.com / Password1)</p>
        <p><a href={{ url_for('user.logout') }}>Sign out</a></p>
    </div>

    <br/>
    <h2>Create a ticket</h2>
    {% from "common/form_macros.html" import render_field, render_submit_field %}
    <form action="" method="POST" class="form" role="form">
    <div class="row">
        <div class="col-sm-6 col-md-5 col-lg-4">
        {{ form.hidden_tag() }}

        {{ render_field(form.title) }}

        {{ render_field(form.description) }}

        {{ render_field(form.status) }}

        {{ render_submit_field(form.submit) }}
        </div>
    </div>

    <br/>
    <h2>Your tickets</h2>
    <ul>
        {% for ticket in tickets %}
            <li><a href="{{ url_for('main.ticket_page', ticket_id=ticket.id) }}">link</a> - {{ ticket }}</li>
        {% endfor %}
    </ul>
</form>
{% endblock %}

app/templates/main/user_profile_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
<h1>User Profile</h1>

<p><a href="{{ url_for('user.change_password') }}">Change password</a></p>

{% from "common/form_macros.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
  <div class="row">
    <div class="col-sm-6 col-md-5 col-lg-4">
    {{ form.hidden_tag() }}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
  </div>
</form>

{% endblock %}